# Experiment
exp_name: alter_emd
dataset: shapenet
cuda: True
parallel: False


# Model
model: consnet
nlayers: 6

# Hyper Parameter
batch_size: 16
test_batch_size: 16
epochs: 100
use_sgd: True
lr: 0.0001
momentum: 0.9
scheduler: cos

num_points: 1024
dropout: 0.5
emb_dims: 1024
k: 20

# Part Segmention
class_choice: None


# Condition
loss: emd
mixup: 3
eval: False
valid: True







